# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CipollinoSys', '0002_auto_20160407_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to='CipollinoSys.Person'),
        ),
    ]
