# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CipollinoSys', '0003_auto_20160407_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=20)),
                ('body', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CipollinoSys.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_boss',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
