# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CipollinoSys', '0007_auto_20160525_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
