# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CipollinoSys', '0008_auto_20160525_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, null=True)),
                ('description', models.TextField(max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CipollinoSys.Department'),
        ),
    ]
